### dns-monitoring/values.ymal
replicaCount: 1

image:
  repository: shinwoohipo/web_dns_monitor
  tag: "1.1.0"
  pullPolicy: Always

service:
  name: http
  type: ClusterIP
  port: 5000 
  targetPort: 5000  # containerPort 로 mapping됨

env:
  - name: IS_DOCKER
    value: "true"
  - name: DNS_FILE
    value: "/etc/pihole/hosts/custom.list"
  - name: GRPC_TARGET
    value: "ping.grpc.sh:5555"

volumeMounts:
  - name: etc-pihole
    mountPath: /etc/pihole
    readOnly: true
  - name: etc-dnsmasq
    mountPath: /etc/dnsmasq.d
    readOnly: true

volumes:
  - name: etc-pihole
    hostPath:
      path: /mnt/pihole/etc-pihole
      type: DirectoryOrCreate
  - name: etc-dnsmasq
    hostPath:
      path: /mnt/pihole/etc-dnsmasq.d
      type: DirectoryOrCreate


resources: {}

nodeSelector:
  dns-role: "true"

tolerations: []
affinity: {}


### ✅ serviceaccount.yaml 용
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

### ✅ ingress-health.yaml 용
### ingress.yaml 에서도  true면 맨 앞단에 추가함.
ingressHealth:
  enabled: true

### ✅ ingress.yaml 용
ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: dns-monitoring.service.sh
      paths:

        - path: /
          pathType: Prefix
          backend:
            service:
              name: dns-monitoring
              port:
                number: 5000
  tls: []

### ✅ httproute.yaml 용 ==> 단순한거라, 그냥 ingress 사용함.
httpRoute:
  enabled: false

### ✅ hpa.yaml 용
autoscaling:
  enabled: false
